[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
regex = "1.11.0"
reqwest = { version = "0.12.8", features = ["blocking"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
